export const tagTypes = {
  auth: "Auth",
  jobBoard: "JobBoard",
  user: "User",
  customer: "Customer",
  profile: "Profile",
  setting: "Setting",
  conversation: "Conversation",
  payment: "Payment",
  feedback: "Feedback",
  promo: "Promo",
  report: "Report",
  overview: "Overview",
  fare: "Fare",
  booking: "Booking",
  snapper: "Snapper",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.jobBoard,
  tagTypes.user,
  tagTypes.customer,
  tagTypes.profile,
  tagTypes.setting,
  tagTypes.conversation,
  tagTypes.payment,
  tagTypes.feedback,
  tagTypes.promo,
  tagTypes.report,
  tagTypes.overview,
  tagTypes.fare,
  tagTypes.booking,
  tagTypes.snapper,
];
